import { useRef, useState } from "react";
import { useReactToPrint } from "react-to-print";
import { QRCodeSVG } from "qrcode.react"; // Standard React SVG QR generator

type Item = { id: string; description: string; qty: number; rate: number };

const bankName = "Revolut";
const bankAccountNumber = "GB46REVO00997031598744";
const bankSwiftNumber = "REVOGB21";

/**
 * Formats a number as Euro currency according to European standards (e.g., 1.000,00 €).
 */
function formatEuro(amount: number): string {
  return new Intl.NumberFormat("de-DE", {
    style: "currency",
    currency: "EUR",
  }).format(amount || 0);
}

/**
 * Generates a structured invoice number based on client name, year, and a sequence.
 */
function generateClientInvoiceNumber(
  clientName: string,
  sequence: number = 1,
): string {
  const currentYear = new Date().getFullYear();

  if (!clientName.trim()) {
    return `INV-${currentYear}-${String(sequence).padStart(4, "0")}`;
  }

  // Clean the client name: remove spaces, accents, and non-alphanumeric characters
  const cleanName = clientName
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-zA-Z0-9]/g, "")
    .toUpperCase();

  // Extract prefix (use first 4 characters, or fewer if the name is short)
  const prefix = cleanName.slice(0, 4) || "INV";
  const paddedSequence = String(sequence).padStart(4, "0");

  return `${prefix}-${currentYear}-${paddedSequence}`;
}

export default function InvoiceApp() {
  const [senderName, setSenderName] = useState("Your Name or Company");
  const [senderAddress, setSenderAddress] = useState(
    "12 Example Street, London, UK",
  );
  const [clientName, setClientName] = useState("Client Company");
  const [clientEmail, setClientEmail] = useState("");
  const [clientAddress, setClientAddress] = useState("Client Address");
  const [invoiceNumber, setInvoiceNumber] = useState("CLIE-2026-0001");
  const [invoiceDate, setInvoiceDate] = useState(
    new Date().toISOString().slice(0, 10),
  );
  const [dueDate, setDueDate] = useState(
    new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().slice(0, 10),
  );
  const [items, setItems] = useState<Item[]>([
    {
      id: String(Date.now()),
      description: "Software development",
      qty: 40,
      rate: 60,
    },
  ]);
  const [vatPercent, setVatPercent] = useState<number>(0);

  // --- Revolut Specific States ---
  const [paymentHandle, setPaymentHandle] = useState("yourrevolutusername");
  const [showQRCode, setShowQRCode] = useState<boolean>(true);

  const invoiceRef = useRef<HTMLDivElement | null>(null);

  function addItem() {
    setItems((s) => [
      ...s,
      {
        id: String(Date.now() + Math.random()),
        description: "",
        qty: 1,
        rate: 0,
      },
    ]);
  }

  function removeItem(id: string) {
    setItems((s) => s.filter((i) => i.id !== id));
  }

  function updateItem(id: string, field: keyof Item, value: string | number) {
    setItems((s) =>
      s.map((it) =>
        it.id === id
          ? ({
              ...it,
              [field]: value,
            } as Item)
          : it,
      ),
    );
  }

  // Handle client name change & generate dynamic invoice ID
  const handleClientNameChange = (newName: string) => {
    setClientName(newName);
    const autoGeneratedId = generateClientInvoiceNumber(newName, 1);
    setInvoiceNumber(autoGeneratedId);
  };

  const subtotal = items.reduce(
    (acc, it) => acc + (it.qty || 0) * (it.rate || 0),
    0,
  );
  const vatAmount = +(subtotal * (vatPercent / 100));
  const total = +(subtotal + vatAmount);

  // --- Pure Revolut Link Builder (Keep standard dot notation for URL safety) ---
  const getPaymentLink = () => {
    const cleanHandle = paymentHandle.trim();
    if (!cleanHandle) return "";
    return `https://revolut.me/${cleanHandle}/${total.toFixed(2)}`;
  };

  const paymentLink = getPaymentLink();

  const handlePrint = useReactToPrint({
    bodyClass: "print-agreement",
    documentTitle: `${invoiceNumber || "invoice"}`,
    onAfterPrint: () => console.log("Printed successfully"),
    contentRef: invoiceRef,
    pageStyle: `
      @page { 
        size: A4; 
        margin: 20mm;
      }
      @media print {
        body { 
          -webkit-print-color-adjust: exact;
          print-color-adjust: exact;
        }
      }
    `,
  });

  async function downloadPDF() {
    handlePrint();
  }

  function openMailClient() {
    const subject = encodeURIComponent(
      `Invoice ${invoiceNumber} from ${senderName}`,
    );
    const bodyLines = [
      `Hi ${clientName},`,
      "",
      `Please find attached invoice ${invoiceNumber} for services provided.`,
      "",
      `Total: ${formatEuro(total)}`,
      paymentLink
        ? `Alternatively, pay directly using this Revolut Link: ${paymentLink}`
        : "",
      "",
      "Kind regards,",
      senderName,
    ];
    const body = encodeURIComponent(bodyLines.join("\n"));
    const mailto = `mailto:${clientEmail}?subject=${subject}&body=${body}`;
    window.open(mailto, "_blank");
  }

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      <div className="max-w-6xl mx-auto">
        <header className="flex items-center justify-between mb-6">
          <h1 className="text-2xl font-bold flex items-center gap-2">
            Parfait Software Solutions
          </h1>
          <div className="space-x-2">
            <button
              onClick={downloadPDF}
              className="px-4 py-2 bg-blue-600 text-white rounded cursor-pointer hover:bg-blue-700"
            >
              Download PDF
            </button>
            <button
              onClick={openMailClient}
              className="px-4 py-2 bg-green-600 text-white rounded cursor-pointer hover:bg-green-700"
            >
              Open Mail Client
            </button>
          </div>
        </header>

        <main className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <form
            className="col-span-1 lg:col-span-1 bg-white p-4 rounded shadow space-y-4"
            onSubmit={(e) => e.preventDefault()}
          >
            <div>
              <h2 className="font-semibold text-lg mb-2 border-b pb-1">
                Invoice Details
              </h2>
              <label className="block text-sm font-semibold mb-1">
                Your name/company
              </label>
              <input
                className="w-full p-2 border rounded mb-2"
                value={senderName}
                onChange={(e) => setSenderName(e.target.value)}
              />
              <label className="block text-sm font-semibold mb-1">
                Your address
              </label>
              <textarea
                className="w-full p-2 border rounded mb-2"
                value={senderAddress}
                onChange={(e) => setSenderAddress(e.target.value)}
              />

              <label className="block text-sm font-semibold mb-1">
                Client name
              </label>
              <input
                className="w-full p-2 border rounded mb-2"
                value={clientName}
                onChange={(e) => handleClientNameChange(e.target.value)}
                placeholder="e.g. Google LLC"
              />
              <label className="block text-sm font-semibold mb-1">
                Client email
              </label>
              <input
                className="w-full p-2 border rounded mb-2"
                value={clientEmail}
                onChange={(e) => setClientEmail(e.target.value)}
              />
              <label className="block text-sm font-semibold mb-1">
                Client address
              </label>
              <textarea
                className="w-full p-2 border rounded mb-2"
                value={clientAddress}
                onChange={(e) => setClientAddress(e.target.value)}
              />

              <label className="block text-sm font-semibold mb-1">
                Invoice #
              </label>
              <input
                className="w-full p-2 border rounded mb-2 font-mono bg-gray-50"
                value={invoiceNumber}
                onChange={(e) => setInvoiceNumber(e.target.value)}
              />

              <div className="flex gap-2">
                <div className="flex-1">
                  <label className="block text-sm font-semibold mb-1">
                    Date
                  </label>
                  <input
                    type="date"
                    className="w-full p-2 border rounded mb-2"
                    value={invoiceDate}
                    onChange={(e) => setInvoiceDate(e.target.value)}
                  />
                </div>
                <div className="flex-1">
                  <label className="block text-sm font-semibold mb-1">
                    Due
                  </label>
                  <input
                    type="date"
                    className="w-full p-2 border rounded mb-2"
                    value={dueDate}
                    onChange={(e) => setDueDate(e.target.value)}
                  />
                </div>
              </div>

              <div className="mt-2">
                <label className="block text-sm font-semibold mb-1">
                  VAT (%)
                </label>
                <input
                  type="number"
                  min={0}
                  className="w-24 p-2 border rounded"
                  value={vatPercent}
                  onChange={(e) => setVatPercent(+e.target.value)}
                />
              </div>
            </div>

            {/* --- Simplified Revolut Only QR Config Panel --- */}
            <div className="bg-slate-50 p-3 rounded border">
              <h3 className="font-bold text-sm mb-2 text-indigo-900">
                ⚡ Revolut QR Payment
              </h3>
              <div className="flex items-center gap-2 mb-3">
                <input
                  type="checkbox"
                  id="show_qr"
                  checked={showQRCode}
                  onChange={(e) => setShowQRCode(e.target.checked)}
                />
                <label
                  htmlFor="show_qr"
                  className="text-sm font-medium cursor-pointer"
                >
                  Show QR on invoice
                </label>
              </div>

              {showQRCode && (
                <div className="space-y-2">
                  <div>
                    <label className="block text-xs font-semibold mb-1 text-gray-600">
                      Revolut.me Username
                    </label>
                    <input
                      type="text"
                      className="w-full p-1.5 border rounded text-sm font-mono"
                      value={paymentHandle}
                      onChange={(e) => setPaymentHandle(e.target.value)}
                      placeholder="e.g. johndoe"
                    />
                    <p className="text-[10px] text-gray-500 mt-1">
                      Link:{" "}
                      <span className="break-all text-indigo-700">
                        {paymentLink}
                      </span>
                    </p>
                  </div>
                </div>
              )}
            </div>
          </form>

          <section className="col-span-1 lg:col-span-2 bg-white p-4 rounded shadow">
            <h2 className="font-semibold mb-4">Line Items</h2>
            <table className="w-full table-auto mb-4">
              <thead>
                <tr className="text-left text-sm">
                  <th>Description</th>
                  <th>Qty</th>
                  <th>Rate</th>
                  <th>Amount</th>
                  <th> </th>
                </tr>
              </thead>
              <tbody>
                {items.map((it) => (
                  <tr key={it.id}>
                    <td>
                      <input
                        className="w-full p-2 border rounded"
                        value={it.description}
                        onChange={(e) =>
                          updateItem(it.id, "description", e.target.value)
                        }
                      />
                    </td>
                    <td className="p-2 w-24">
                      <input
                        type="number"
                        className="w-full p-2 border rounded"
                        value={it.qty}
                        onChange={(e) =>
                          updateItem(it.id, "qty", +e.target.value)
                        }
                      />
                    </td>
                    <td className="p-2 w-32">
                      <input
                        type="number"
                        className="w-full p-2 border rounded"
                        value={it.rate}
                        onChange={(e) =>
                          updateItem(it.id, "rate", +e.target.value)
                        }
                      />
                    </td>
                    <td className="p-2">{formatEuro(it.qty * it.rate)}</td>
                    <td className="p-2">
                      <button
                        type="button"
                        className="px-3 py-2 bg-red-500 text-white rounded cursor-pointer hover:bg-red-600"
                        onClick={() => removeItem(it.id)}
                      >
                        Remove
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            <div className="mb-4">
              <button
                type="button"
                className="px-3 py-2 bg-indigo-600 text-white rounded cursor-pointer hover:bg-indigo-700"
                onClick={addItem}
              >
                Add item
              </button>
            </div>

            <div className="flex justify-end space-y-1 flex-col">
              <div className="flex justify-between w-full max-w-sm">
                <span>Subtotal</span>
                <span>{formatEuro(subtotal)}</span>
              </div>
              <div className="flex justify-between w-full max-w-sm">
                <span>VAT ({vatPercent}%)</span>
                <span>{formatEuro(vatAmount)}</span>
              </div>
              <div className="flex justify-between w-full max-w-sm font-bold text-lg mt-2">
                <span>Total</span>
                <span>{formatEuro(total)}</span>
              </div>
            </div>
          </section>

          {/* --- Preview & Print Container --- */}
          <aside className="col-span-1 lg:col-span-3">
            <h2 className="font-semibold mb-2">Preview</h2>
            <div
              ref={invoiceRef}
              className="bg-white p-6 rounded shadow w-full max-w-3xl mx-auto border"
            >
              <div className="flex justify-between">
                <div>
                  <h3 className="text-xl font-bold">{senderName}</h3>
                  <div className="whitespace-pre-line text-sm text-gray-700">
                    {senderAddress}
                  </div>
                </div>
                <div className="text-right">
                  <h4 className="font-semibold">Invoice</h4>
                  <div className="font-mono text-sm font-bold text-indigo-900">
                    #{invoiceNumber}
                  </div>
                  <div>Date: {invoiceDate}</div>
                  <div>Due: {dueDate}</div>
                </div>
              </div>

              <div className="mt-6 grid grid-cols-2 gap-4">
                <div>
                  <div className="text-sm text-gray-600">Bill To</div>
                  <div className="font-semibold">{clientName}</div>
                  <div className="whitespace-pre-line text-sm">
                    {clientAddress}
                  </div>
                </div>
                <div className="text-sm">
                  <div className="font-semibold">Standard Bank Transfer</div>
                  <div className="mt-1 text-gray-700">Bank: {bankName}</div>
                  <div className="text-gray-700">
                    Account (IBAN): {bankAccountNumber}
                  </div>
                  <div className="text-gray-700">
                    BIC / SWIFT: {bankSwiftNumber}
                  </div>
                </div>
              </div>

              <table className="w-full mt-6 text-sm table-fixed">
                <thead>
                  <tr className="border-b">
                    <th className="text-left pb-2">Description</th>
                    <th className="text-right pb-2 w-16">Qty</th>
                    <th className="text-right pb-2 w-24">Rate</th>
                    <th className="text-right pb-2 w-24">Amount</th>
                  </tr>
                </thead>
                <tbody>
                  {items.map((it) => (
                    <tr key={it.id} className="border-b border-gray-100">
                      <td className="py-2">{it.description}</td>
                      <td className="py-2 text-right">{it.qty}</td>
                      <td className="py-2 text-right">{formatEuro(it.rate)}</td>
                      <td className="py-2 text-right">
                        {formatEuro(it.qty * it.rate)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>

              <div className="mt-6 grid grid-cols-1 md:grid-cols-2 gap-4 items-start">
                {/* Payment QR Code Rendering Area (Revolut Exclusive) */}
                <div>
                  {showQRCode && paymentLink && (
                    <div className="border rounded-xl p-3 bg-slate-50 flex items-center gap-4 max-w-sm">
                      <div className="bg-white p-1 rounded border">
                        <QRCodeSVG
                          value={paymentLink}
                          size={90}
                          level="M"
                          includeMargin={false}
                        />
                      </div>
                      <div>
                        <p className="text-xs font-bold text-gray-800 uppercase tracking-wider">
                          Scan to pay
                        </p>
                        <p className="text-[11px] text-gray-500 mt-0.5 leading-tight">
                          Scan with your mobile camera to pay instantly via
                          **Revolut** for {formatEuro(total)}.
                        </p>
                        <a
                          href={paymentLink}
                          target="_blank"
                          rel="noreferrer"
                          className="text-[10px] text-indigo-600 underline block mt-2 hover:text-indigo-800"
                        >
                          Direct Payment Link
                        </a>
                      </div>
                    </div>
                  )}
                </div>

                {/* Subtotals & Grand Totals */}
                <div className="text-sm">
                  <div className="flex justify-between py-1">
                    <span>Subtotal</span>
                    <span>{formatEuro(subtotal)}</span>
                  </div>
                  <div className="flex justify-between py-1">
                    <span>VAT ({vatPercent}%)</span>
                    <span>{formatEuro(vatAmount)}</span>
                  </div>
                  <div className="flex justify-between border-t pt-2 font-bold text-gray-900 text-lg">
                    <span>Total</span>
                    <span>{formatEuro(total)}</span>
                  </div>
                </div>
              </div>

              <div className="mt-8 pt-4 border-t text-xs text-gray-500">
                Notes: Payment due within 14 days. Thank you for your business.
              </div>
            </div>
          </aside>
        </main>
      </div>
    </div>
  );
}
